include(CMakeFindDependencyMacro)
find_dependency(Boost 1.80 COMPONENTS container json)
if (WIN32)
  find_dependency(RocksDB)
  find_dependency(flatbuffers)
endif (WIN32)
find_dependency(Threads)
find_dependency(ZLIB)
find_dependency(NanoLog)
include(${CMAKE_CURRENT_LIST_DIR}/ConfigDbCommonTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ConfigDbLibTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ConfigDbApiTargets.cmake)
