# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

class ValueVariant(object):
    NONE = 0
    Value = 1
    Children = 2
    Success = 3

def ValueVariantCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == ValueVariant().Value:
        import spt.configdb.model.Value
        return spt.configdb.model.Value.ValueT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ValueVariant().Children:
        import spt.configdb.model.Children
        return spt.configdb.model.Children.ChildrenT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ValueVariant().Success:
        import spt.configdb.model.Success
        return spt.configdb.model.Success.SuccessT.InitFromBuf(table.Bytes, table.Pos)
    return None
